[package]
name = "blog"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
axum = "0.7.7"
base64 = "0.22.1"
chrono = "0.4.38"
env_logger = "0.11.5"
envy = "0.4.2"
futures-util = "0.3.31"
gateway-api = { git = "https://github.com/llenotre/gateway.git" }
lol_html = "2.0.0"
maxminddb = "0.24.0"
pulldown-cmark = "0.12.2"
reqwest = { version = "0.12.9", features = ["json", "stream"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
serde_with = "3.11.0"
tokio = { version = "1.41.1", features = ["rt-multi-thread"] }
tokio-util = "0.7.12"
toml = "0.8.19"
tower-http = { version = "0.6.1", features = ["fs", "trace"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
uaparser = "0.6.4"

[profile.release]
lto = true
strip = true
