[package]
name = "blog"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
axum = "0.7.9"
chrono = "0.4.39"
envy = "0.4.2"
gateway-api = { git = "https://github.com/llenotre/gateway.git" }
lol_html = "2.1.0"
pulldown-cmark = "0.12.2"
serde = { version = "1.0.216", features = ["derive"] }
tokio = { version = "1.42.0", features = ["rt-multi-thread"] }
toml = "0.8.19"
tower-http = { version = "0.6.2", features = ["fs"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[profile.release]
lto = true
strip = true

[features]
analytics = []