[package]
name = "blog"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.2"
actix-multipart = "0.6.0"
actix-session = { version = "0.7.2", features = ["cookie-session"] }
actix-web = { version = "4.3.1", features = ["cookies"] }
ammonia = "3.3.0"
async-recursion = "1.0.4"
base64 = "0.21.2"
bson = { version = "2.6.1", features = ["chrono-0_4"] }
chrono = "0.4.24"
env_logger = "0.10.0"
futures-util = "0.3.28"
lazy_static = "1.4.0"
mongodb = "2.4.0"
pulldown-cmark = "0.9.2"
regex = "1.8.3"
reqwest = { version = "0.11.16", features = ["json", "stream"] }
serde = { version = "1.0.160", features = ["derive"] }
tokio = "1.27.0"
tokio-util = "0.7.8"
toml = "0.7.3"
tracing = "*"
