[package]
name = "blog"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-files = "0.6.2"
actix-web = "4.3.1"
env_logger = "0.10.0"
serde = { version = "1.0.160", features = ["derive"] }
toml = "0.7.3"
