port = 80

pg_conn = "host= dbname= user= password="

client_id = "..."
client_secret = "..."

session_secret_key = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

discord_invite = ""
