port = 80
mongo_url = "mongodb://localhost:27017"

client_id = "..."
client_secret = "..."

session_secret_key = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

discord_invite = ""
