services:
  web:
    build: web/
    depends_on:
      - db
    restart: always
    ports:
      - 127.0.0.1:8080:8080
  db:
    build: db/
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRESQL_USERNAME: blog
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
    volumes:
      - ./db/.aws:/root/.aws
