services:
  web:
    build: .
    depends_on:
      - db
    restart: always
    ports:
      - 127.0.0.1:8080:8080
  db:
    build: db/
    restart: always
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: blog
      POSTGRES_PASSWORD_FILE: /run/secrets/dbpass
    volumes:
      - ./db/.aws:/root/.aws
    secrets:
      - dbpass
secrets:
  dbpass:
    file: .dbpass
