services:
  web:
    build: .
    depends_on:
      - mongo
    restart: always
    ports:
      - 8080:8080
  mongo:
    image: mongo:7.0.0-rc7
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
  backup:
    build: backup/
    depends_on:
      - mongo
    restart: always
    environment:
      MONGO_ROOT_USERNAME: root
      MONGO_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    volumes:
      - ./backup/.aws:/root/.aws
